AWSTemplateFormatVersion: 2010-09-09
Description: >-
  cloudwatch-alarm-to-discord

  Send CloudWatch Alarms to Discord via an SNS topic.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: cloudwatch-alarm-to-discord
    Description: Send CloudWatch Alarms to Discord via an SNS topic.
    Author: Zero Based Ltd - Jamie Wood
    Labels: [ 'cloudwatch','discord','notification' ]
    HomePageUrl: https://github.com/woodjme/cloudwatch-alarm-to-discord
    ReadmeUrl: README.md
    SemanticVersion: 1.0.2
    SourceCodeUrl: https://github.com/woodjme/cloudwatch-alarm-to-discord
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Parameters:
  AlarmTopicArn:
    Type: String
    Description: ARN of the SNS topic that receives the CloudWatch Alarms you want to forward to Discord.
  DiscordWebhookUrl:
    Type: String
    Description: The URL of the Discord webhook to which you want to send alarm notifications.

Transform:
- AWS::Serverless-2016-10-31

Resources:
  ForwardToDiscordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Description: Function for forwarding CloudWatch Alarms to Discord.
      Handler: dist/handlers/index.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Events:
        AlarmNotification:
          Type: SNS
          Properties:
            Topic: !Ref AlarmTopicArn
